# render.yaml  (put at the repo root)

services:
  # ───────────────────────────
  # Backend (FastAPI + Postgres)
  # ───────────────────────────
  - type: web
    name: wmis-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: bash scripts/migrate_then_start.sh
    envVars:
      # Render injects the DB connection string
      - key: DATABASE_URL
        fromDatabase:
          name: wmis-db
          property: connectionString

      # Random secret for JWTs (Render will generate a secret value)
      - key: JWT_SECRET
        generateValue: true

      # IMPORTANT: after the frontend is live, replace this with the actual
      # onrender.com URL shown on the frontend service (https://…onrender.com)
      - key: CORS_ORIGINS
        value: https://wmis-frontend.onrender.com

      # Where your QR links should point (you can change later)
      - key: DRIVER_QR_BASE_URL
        value: https://example.com

    autoDeploy: true

  # ───────────────────────────
  # Frontend (Vite static site)
  # ───────────────────────────
  - type: static_site          # ← NOTE: must be static_site (not static)
    name: wmis-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      # After backend deploy, copy the backend’s public URL (https://…onrender.com)
      # and paste it here so the built app calls the live API
      - key: VITE_API_URL
        value: https://wmis-backend.onrender.com

databases:
  - name: wmis-db
    plan: free
